(() => {
  'use strict';
  const API = '/api/admin';
  const state = { view: 'overview', info: null, token: sessionStorage.getItem('iris_access_token') };
  const catalog = {
    security: [['/v2/security/users','Users','View IRIS security users','Secure'],['/v2/security/roles','Roles','View available security roles','Secure'],['/v2/security/resources','Resources','Inspect permission resources','Secure'],['/v2/security/services','Services','Inspect configured services','Secure'],['/v2/security/oauth2/client/client-configurations','OAuth clients','Review OAuth client configuration','OAuth2 Client'],['/v2/security/x509-credentials','X.509 credentials','Inspect certificate credentials','Secure'],['/v2/wallet/collections','Wallet collections','Review secure wallet collections','Wallet'],['/v2/security/audit/events','Audit events','Review security audit events','Secure']],
    operations: [['/v2/tasks','Tasks','View scheduled tasks','Operate / Task'],['/v2/task/manager','Task manager','Inspect task manager state','Task'],['/v2/processes','Processes','Inspect active processes','Operate'],['/v2/monitor/dashboard/main','Dashboard metrics','Read operational dashboard statistics','Operate'],['/v2/monitor/dashboard/system-resources','System resources','Read CPU and memory dashboards','Operate'],['/v2/locks','Locks','Inspect system locks','Operate']],
    system: [['/v2/databases','Databases','List configured databases','Manage / Operate'],['/v2/namespaces','Namespaces','List IRIS namespaces','Manage'],['/v2/web-apps','Web applications','View deployed web applications','Secure'],['/v2/devices','Devices','Inspect configured devices','Operate'],['/v2/database-dir/volumes','Disk volumes','Inspect database volumes','Manage'],['/v2/journal/files','Journal files','List journal files','Journal']],
    observability: [['/v2/security/audit/events','Audit events','Review security audit events','Secure'],['/v2/security/audit/records','Audit records','Inspect recorded audit entries','Secure'],['/v2/journal/files','Journal files','List journal files and status','Journal'],['/v2/journal/settings','Journal settings','Inspect journal configuration','Journal'],['/v2/monitor/system-usage','System usage','Read system usage statistics','Operate'],['/v2/monitor/license-usage','License usage','Read license usage statistics','Operate']]
  };
  const $ = (selector) => document.querySelector(selector);
  const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const pretty = (value) => JSON.stringify(value, null, 2);
  function showNotice(message, kind = 'error') { const node = $('#notice'); node.textContent = message; node.className = `notice ${kind}`; if (!message) node.classList.add('hidden'); }
  async function request(path, options = {}) {
    const headers = { Accept: 'application/json', ...(options.headers || {}) };
    if (options.body && typeof options.body !== 'string') { headers['Content-Type'] = 'application/json'; options.body = JSON.stringify(options.body); }
    if (state.token) headers.Authorization = `Bearer ${state.token}`;
    const response = await fetch(`${API}${path}`, { ...options, headers }); const text = await response.text();
    let data; try { data = text ? JSON.parse(text) : {}; } catch (_) { data = { raw: text }; }
    if (!response.ok) throw new Error(data?.message || data?.error || `Request failed (${response.status})`); return data;
  }
  function setConnection(connected) { $('#open-login').classList.toggle('hidden', connected); $('#logout').classList.toggle('hidden', !connected); $('#session-label').textContent = connected ? (state.info?.username || 'Connected') : 'Not connected'; $('#server-chip').textContent = connected ? (state.info?.serverVersion || 'IRIS connected') : 'No server'; $('#server-chip').className = `chip ${connected ? '' : 'muted'}`; }
  function card(title, value, note, tone = '') { return `<article class="metric-card ${tone}"><span class="metric-label">${esc(title)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`; }
  function renderJson(title, data) { return `<div class="result-panel"><div class="result-head"><h3>${esc(title)}</h3><button class="button tiny copy-json">Copy JSON</button></div><pre>${esc(pretty(data))}</pre></div>`; }
  async function loadInfo() { state.info = await request('/info'); setConnection(true); return state.info; }
  function renderOverview() {
    const info = state.info;
    if (!info) return `<div class="empty-state"><div class="empty-icon">◈</div><h2>Connect to an IRIS server</h2><p>Use the management API to inspect your environment from one focused workspace.</p><button class="button primary" id="empty-connect">Connect to IRIS</button></div>`;
    const privileges = Object.entries(info.privileges || {}).filter(([, value]) => value?.use).map(([key]) => key);
    return `<div class="hero"><div><p class="eyebrow">SERVER</p><h2>${esc(info.product || 'IRIS').toUpperCase()} server information</h2><p class="muted-text">${esc(info.serverVersion || 'Version unavailable')}</p></div><span class="live-badge"><i></i> Connected</span></div><div class="metrics">${card('Product', info.product || '—', `API v${info.apiVersion ?? '—'}`)}${card('Username', info.username || '—', info.systemMode || 'Mode unavailable', 'violet')}${card('Namespaces', info.namespaces?.length ?? 0, 'Visible to this session', 'orange')}${card('Admin scopes', privileges.length, privileges.length ? privileges.join(', ') : 'No scopes reported', 'green')}</div><div class="section-heading"><div><p class="eyebrow">NAVIGATION</p><h2>Common views</h2></div></div><div class="quick-grid">${quick('security','Security','Users, roles, services and audit events','◉')}${quick('operations','Operations','Tasks, processes and live metrics','▣')}${quick('system','System','Databases, namespaces and web apps','⌘')}${quick('explorer','API Explorer','Run GET requests against the API','⌁')}</div>${renderJson('Session information', info)}`;
  }
  function quick(view, title, text, icon) { return `<button class="quick-card" data-view="${view}"><span class="quick-icon">${icon}</span><span><strong>${title}</strong><small>${text}</small></span><b>→</b></button>`; }
  async function renderCatalog(group) {
    const title = group === 'observability' ? 'Logs & Insights' : group[0].toUpperCase() + group.slice(1); $('#view').innerHTML = `<div class="section-heading"><div><p class="eyebrow">READ-ONLY SHORTCUTS</p><h2>${title}</h2><p class="muted-text">Each card calls the corresponding IRIS management API and shows the raw response.</p></div></div><div class="endpoint-grid">${catalog[group].map(([path,name,desc,scope]) => `<article class="endpoint-card"><div class="endpoint-top"><span class="method">GET</span><span class="scope">${esc(scope)}</span></div><h3>${esc(name)}</h3><p>${esc(desc)}</p><code>${esc(path)}</code><button class="button secondary run-endpoint" data-path="${esc(path)}" data-name="${esc(name)}">Run request</button><div class="endpoint-result hidden"></div></article>`).join('')}</div>`;
    $('#view').querySelectorAll('.run-endpoint').forEach((button) => button.addEventListener('click', () => runEndpoint(button)));
  }
  async function runEndpoint(button) { const cardNode = button.closest('.endpoint-card'); const result = cardNode.querySelector('.endpoint-result'); button.disabled = true; button.textContent = 'Loading…'; result.classList.remove('hidden'); result.innerHTML = '<div class="spinner"></div>'; try { result.innerHTML = renderJson(button.dataset.name, await request(button.dataset.path)); } catch (error) { result.innerHTML = `<div class="inline-error">${esc(error.message)}</div>`; } finally { button.disabled = false; button.textContent = 'Run again'; } }
  function renderExplorer() { const endpoints = Object.values(catalog).flat(); $('#view').innerHTML = `<div class="section-heading"><div><p class="eyebrow">OPENAPI-ALIGNED</p><h2>API Explorer</h2><p class="muted-text">Try the most useful read endpoints from the IRIS management API.</p></div></div><div class="explorer"><label>Endpoint<select id="endpoint-select">${endpoints.map(([path,name]) => `<option value="${esc(path)}">GET ${esc(path)} — ${esc(name)}</option>`).join('')}</select></label><button class="button primary" id="explore-run">Run GET</button></div><div id="explorer-result"></div><div class="tip"><strong>Safety note</strong><span>This first version exposes GET operations only. Mutating actions remain intentionally outside the quick explorer.</span></div>`; $('#explore-run').addEventListener('click', async () => { const path = $('#endpoint-select').value; $('#explorer-result').innerHTML = '<div class="result-panel"><div class="spinner"></div></div>'; try { $('#explorer-result').innerHTML = renderJson(path, await request(path)); } catch (error) { $('#explorer-result').innerHTML = `<div class="inline-error">${esc(error.message)}</div>`; } }); }
  async function render(view = state.view) { state.view = view; document.querySelectorAll('.nav-item').forEach((button) => button.classList.toggle('active', button.dataset.view === view)); $('#page-title').textContent = view === 'overview' ? 'Overview' : view === 'explorer' ? 'API Explorer' : view[0].toUpperCase() + view.slice(1); showNotice(''); if (view === 'overview') { $('#view').innerHTML = '<div class="loading"><div class="spinner"></div><span>Loading server information…</span></div>'; if (state.token) { try { await loadInfo(); } catch (error) { state.token = null; sessionStorage.removeItem('iris_access_token'); setConnection(false); showNotice(error.message); } } $('#view').innerHTML = renderOverview(); } else if (view === 'explorer') renderExplorer(); else if (!state.token) $('#view').innerHTML = `<div class="empty-state"><div class="empty-icon">🔐</div><h2>Authentication required</h2><p>Connect to IRIS to access this view.</p><button class="button primary" id="view-connect">Connect to IRIS</button></div>`; else await renderCatalog(view); $('#view').querySelectorAll('[data-view]').forEach((button) => button.addEventListener('click', () => render(button.dataset.view))); $('#view').querySelectorAll('.copy-json').forEach((button) => button.addEventListener('click', () => navigator.clipboard?.writeText(button.closest('.result-panel').querySelector('pre').textContent))); $('#empty-connect, #view-connect')?.addEventListener('click', () => $('#login-dialog').showModal()); }
  $('#login-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const submit = event.currentTarget.querySelector('button[type=submit]'); submit.disabled = true; submit.textContent = 'Connecting…'; try { const result = await request('/login', { method: 'POST', body: { user: form.get('user'), password: form.get('password'), ...(form.get('role') ? { role: form.get('role') } : {}) } }); state.token = result.result?.access_token; if (!state.token) throw new Error('The server did not return an access token.'); sessionStorage.setItem('iris_access_token', state.token); await loadInfo(); $('#login-dialog').close(); await render(state.view); } catch (error) { showNotice(error.message); } finally { submit.disabled = false; submit.textContent = 'Connect securely'; } });
  $('#open-login').addEventListener('click', () => $('#login-dialog').showModal()); $('#close-login').addEventListener('click', () => $('#login-dialog').close()); $('#logout').addEventListener('click', async () => { try { if (state.token) await request('/logout', { method: 'POST' }); } catch (_) {} state.token = null; state.info = null; sessionStorage.removeItem('iris_access_token'); setConnection(false); render('overview'); }); document.querySelectorAll('.nav-item').forEach((button) => button.addEventListener('click', () => render(button.dataset.view))); setConnection(Boolean(state.token)); render('overview');
})();
